name: Ping Pong

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping Pong
    steps:
      - name: Checking the Panahifar.ir
        id: Hi
        uses: srt32/uptime@master
        with:
          url-to-hit: "http://panahifar.ir/"
          expected-statuses: "200,301"